---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: app-cd-pipeline-run
spec:
  pipelineRef:
    name: app-cd-pipeline
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc
  params:
    - name: git-url
      value: https://github.com/mualiyu/ci-cd-final-project.git
    - name: git-revision
      value: main
    - name: app-name
      value: my-python-app
    - name: build-image
      value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/my-python-app:latest
